project:
  type: website
  resources:
    - Tyler_Chia_Resume_.pdf

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Courses
        
  page-footer: 
    right: "&copy; Tyler Jordan Chia"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

