project:
  type: website
  resources:
    - Tyler_Chia_Resume_.pdf

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: experience.qmd
        text: Experience
      - href: courses.qmd
        text: Coursework
      - href: projects.qmd
        text: Projects
        
  page-footer: 
    right: "&copy; Tyler Jordan Chia"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    anchor-sections: false

editor: visual

